### ISSUE TITLE
Request server update information

### ISSUE THREAD

**Issue by escoand** [meichthys/nextcloud_monitor#7]
With Nextcloud 28 the serverinfo add-on is able to provide information of available updates. But this is opt-in depending on an GET parameter. Could you please add this parameter to the URL? Not sure if this is privacy related.

See https://github.com/nextcloud/serverinfo/pull/522/files

**Comment by escoand** [comment]
@meichthys May I kindly request a new pypi release? The home assistant PR is waiting for it.

**Comment by meichthys** [comment]
@escoand  And... done :)
